### ISSUE TITLE
match 테스트코드 수정

### ISSUE THREAD

**Issue by Sangddong** [team-sweatier/sweatier-server#166]
- match 서비스 테스트 코드 일부 수정
- 모집글 생성 성공 케이스 수정

<전> 
<img width="464" alt="스크린샷 2024-09-27 오후 2 22 57" src="https://github.com/user-attachments/assets/dfc5115e-87bf-47af-905e-4315227e1537">

<후>
<img width="474" alt="스크린샷 2024-09-27 오후 2 22 05" src="https://github.com/user-attachments/assets/34481364-200d-49bc-8e06-819d685e2b72">

**Comment by mpfo0106** [comment]
PR 이 올라온게 없네요

**Comment by Sangddong** [comment]
> PR 이 올라온게 없네요

어라라?? 저녁에 집가서 수정하겠습니다 ㅎㅎ;, 죗옹합니다
